@@include('plagins/jquery-migrate-3.0.0.js')
@@include('plagins/slick.js')
@@include('plagins/select2.js')
@@include('plagins/jquery-ui.js')
@@include('plagins/jquery.fancybox.js')
@@include('plagins/jquery.maskedinput.js')
@@include('plagins/bootstrap.js')
@@include('plagins/jquery.touchSwipe.js')

@@include('custom/custom.js')
